server:
  port: 8071
spring:
  application:
    name: pet-service
  datasource:
    url: jdbc:mysql://rm-8vbn98pnn0mbemwv72o.mysql.zhangbei.rds.aliyuncs.com:3306/pet_manage?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=UTF8
    username: quan_zhang
    password: zhangquan123234
    hikari:
      maximum-pool-size: 30
      minimum-idle: 10
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}